import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'Ibnalshaekh API',
            version: '1.0.0',
            description: 'API documentation for Ibnalshaekh Construction Company backend',
            contact: {
                name: 'Ibnalshaekh',
                email: 'info@ibnalshaekh.com',
            },
        },
        servers: [
            {
                url: process.env.SWAGGER_DEV_URL || 'http://localhost:5000/api',
                description: 'Development server',
            },
            {
                url: process.env.SWAGGER_PROD_URL || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}/api` : 'https://api.ibnalshaekh.com'),
                description: 'Production server',
            },
        ],
        components: {
            securitySchemes: {
                bearerAuth: {
                    type: 'http',
                    scheme: 'bearer',
                    bearerFormat: 'SessionID',
                    description: 'Session ID obtained from login endpoint',
                },
            },
            schemas: {
                // ─── User ───
                User: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string', description: 'User ID' },
                        userName: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        role: { type: 'string', enum: ['admin', 'user'] },
                        tel: { type: 'string', nullable: true },
                        photo: { type: 'string', nullable: true },
                        yearsOfExp: { type: 'integer', nullable: true },
                        descriptionAr: { type: 'string', nullable: true },
                        descriptionEn: { type: 'string', nullable: true },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateUserInput: {
                    type: 'object',
                    required: ['userName', 'passwordHash'],
                    properties: {
                        userName: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        passwordHash: { type: 'string', description: 'Password (will be hashed)' },
                        role: { type: 'string', enum: ['admin', 'user'], default: 'user' },
                        tel: { type: 'string' },
                        photo: { type: 'string' },
                        yearsOfExp: { type: 'integer' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                    },
                },
                // ─── Session ───
                Session: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string', description: 'Session ID (used as Bearer token)' },
                        userId: { type: 'string', description: 'Reference to User' },
                        expiresAt: { type: 'string', format: 'date-time' },
                    },
                },
                // ─── Project ───
                Project: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        locationAr: { type: 'string' },
                        locationEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        fullDescriptionAr: { type: 'string' },
                        fullDescriptionEn: { type: 'string' },
                        durationAr: { type: 'string' },
                        durationEn: { type: 'string' },
                        teamAr: { type: 'string' },
                        teamEn: { type: 'string' },
                        workersCount: { type: 'integer', nullable: true, description: 'Number of workers' },
                        engineersCount: { type: 'integer', nullable: true, description: 'Number of engineers' },
                        injuredCount: { type: 'integer', nullable: true, description: 'Number of injuries' },
                        actualDurationAr: { type: 'string', nullable: true },
                        actualDurationEn: { type: 'string', nullable: true },
                        area: { type: 'string' },
                        status: { type: 'string' },
                        categoryId: { type: 'string', description: 'Reference to Category' },
                        techStack: { type: 'array', items: { type: 'string' } },
                        gallery: { type: 'array', items: { type: 'string' } },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateProjectInput: {
                    type: 'object',
                    required: [
                        'titleAr', 'titleEn', 'locationAr', 'locationEn',
                        'descriptionAr', 'descriptionEn', 'categoryId', 'status',
                    ],
                    properties: {
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        locationAr: { type: 'string' },
                        locationEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        fullDescriptionAr: { type: 'string' },
                        fullDescriptionEn: { type: 'string' },
                        durationAr: { type: 'string' },
                        durationEn: { type: 'string' },
                        teamAr: { type: 'string' },
                        teamEn: { type: 'string' },
                        workersCount: { type: 'integer' },
                        engineersCount: { type: 'integer' },
                        injuredCount: { type: 'integer' },
                        actualDurationAr: { type: 'string' },
                        actualDurationEn: { type: 'string' },
                        area: { type: 'string' },
                        status: { type: 'string' },
                        categoryId: { type: 'string' },
                        techStack: { type: 'array', items: { type: 'string' } },
                        gallery: { type: 'array', items: { type: 'string' } },
                    },
                },
                UpdateProjectInput: {
                    type: 'object',
                    properties: {
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        locationAr: { type: 'string' },
                        locationEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        fullDescriptionAr: { type: 'string' },
                        fullDescriptionEn: { type: 'string' },
                        durationAr: { type: 'string' },
                        durationEn: { type: 'string' },
                        teamAr: { type: 'string' },
                        teamEn: { type: 'string' },
                        workersCount: { type: 'integer' },
                        engineersCount: { type: 'integer' },
                        injuredCount: { type: 'integer' },
                        actualDurationAr: { type: 'string' },
                        actualDurationEn: { type: 'string' },
                        area: { type: 'string' },
                        status: { type: 'string' },
                        categoryId: { type: 'string' },
                        techStack: { type: 'array', items: { type: 'string' } },
                        gallery: { type: 'array', items: { type: 'string' } },
                    },
                },
                // ─── Category ───
                Category: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        color: { type: 'string', description: 'Hex color code' },
                        countAr: { type: 'string' },
                        countEn: { type: 'string' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateCategoryInput: {
                    type: 'object',
                    required: ['titleAr', 'titleEn', 'descriptionAr', 'descriptionEn', 'color', 'countAr', 'countEn'],
                    properties: {
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        color: { type: 'string' },
                        countAr: { type: 'string' },
                        countEn: { type: 'string' },
                    },
                },
                // ─── Service ───
                BilingualField: {
                    type: 'object',
                    properties: {
                        ar: { type: 'string' },
                        en: { type: 'string' },
                    },
                },
                Service: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        slug: { type: 'string', description: 'URL slug (unique)' },
                        title: { $ref: '#/components/schemas/BilingualField' },
                        shortDescription: { $ref: '#/components/schemas/BilingualField' },
                        fullDescription: { $ref: '#/components/schemas/BilingualField' },
                        icon: { type: 'string' },
                        features: {
                            type: 'array',
                            items: { $ref: '#/components/schemas/BilingualField' },
                        },
                        benefits: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    title: { $ref: '#/components/schemas/BilingualField' },
                                    description: { $ref: '#/components/schemas/BilingualField' },
                                },
                            },
                        },
                        process: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    step: { type: 'integer' },
                                    title: { $ref: '#/components/schemas/BilingualField' },
                                    description: { $ref: '#/components/schemas/BilingualField' },
                                },
                            },
                        },
                        images: { type: 'array', items: { type: 'string' } },
                        stats: {
                            type: 'object',
                            properties: {
                                projects: { type: 'string' },
                                experience: { type: 'string' },
                                satisfaction: { type: 'string' },
                            },
                        },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateServiceInput: {
                    type: 'object',
                    required: ['slug', 'title'],
                    properties: {
                        slug: { type: 'string' },
                        title: { $ref: '#/components/schemas/BilingualField' },
                        shortDescription: { $ref: '#/components/schemas/BilingualField' },
                        fullDescription: { $ref: '#/components/schemas/BilingualField' },
                        icon: { type: 'string' },
                        features: { type: 'array', items: { $ref: '#/components/schemas/BilingualField' } },
                        benefits: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    title: { $ref: '#/components/schemas/BilingualField' },
                                    description: { $ref: '#/components/schemas/BilingualField' },
                                },
                            },
                        },
                        process: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    step: { type: 'integer' },
                                    title: { $ref: '#/components/schemas/BilingualField' },
                                    description: { $ref: '#/components/schemas/BilingualField' },
                                },
                            },
                        },
                        images: { type: 'array', items: { type: 'string' } },
                        stats: {
                            type: 'object',
                            properties: {
                                projects: { type: 'string' },
                                experience: { type: 'string' },
                                satisfaction: { type: 'string' },
                            },
                        },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                    },
                },
                // ─── Department ───
                Department: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        icon: { type: 'string' },
                        sections: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    _id: { type: 'string' },
                                    titleAr: { type: 'string' },
                                    titleEn: { type: 'string' },
                                    icon: { type: 'string' },
                                },
                            },
                        },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateDepartmentInput: {
                    type: 'object',
                    required: ['titleAr', 'titleEn'],
                    properties: {
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        icon: { type: 'string' },
                        sections: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    titleAr: { type: 'string' },
                                    titleEn: { type: 'string' },
                                    icon: { type: 'string' },
                                },
                            },
                        },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                    },
                },
                QualityStandard: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        icon: { type: 'string' },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateQualityStandardInput: {
                    type: 'object',
                    required: ['titleAr', 'titleEn', 'descriptionAr', 'descriptionEn'],
                    properties: {
                        titleAr: { type: 'string' },
                        titleEn: { type: 'string' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                        icon: { type: 'string' },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                    },
                },
                // ─── Employee ───
                Employee: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        user: { type: 'string', description: 'Reference to User ID' },
                        firstName: { type: 'string' },
                        lastName: { type: 'string' },
                        phoneNumber: { type: 'string' },
                        employeeId: { type: 'string', description: 'Unique employee identifier' },
                        position: { type: 'string', enum: ['engineer', 'technician', 'supervisor', 'manager'] },
                        department: { type: 'string' },
                        hireDate: { type: 'string', format: 'date' },
                        ssn: { type: 'string', description: 'Only visible to self and admin' },
                        dateOfBirth: { type: 'string', format: 'date' },
                        address: { type: 'string' },
                        emergencyContact: { type: 'string' },
                        projects: { type: 'array', items: { type: 'string' }, description: 'Array of Project IDs' },
                        skills: { type: 'array', items: { type: 'string' } },
                        salary: { type: 'number', description: 'Only visible to self and admin' },
                        isActive: { type: 'boolean' },
                        joinDate: { type: 'string', format: 'date' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateEmployeeInput: {
                    type: 'object',
                    required: ['firstName', 'lastName', 'email', 'password', 'phoneNumber', 'employeeId', 'position', 'department', 'hireDate'],
                    properties: {
                        firstName: { type: 'string' },
                        lastName: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        password: { type: 'string' },
                        phoneNumber: { type: 'string' },
                        employeeId: { type: 'string' },
                        position: { type: 'string', enum: ['engineer', 'technician', 'supervisor', 'manager'] },
                        department: { type: 'string' },
                        hireDate: { type: 'string', format: 'date' },
                        skills: { type: 'array', items: { type: 'string' } },
                        salary: { type: 'number' },
                    },
                },
                // ─── Partner ───
                Partner: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        name: { $ref: '#/components/schemas/BilingualField' },
                        logo: { type: 'string' },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreatePartnerInput: {
                    type: 'object',
                    required: ['logo'],
                    properties: {
                        name: { $ref: '#/components/schemas/BilingualField' },
                        logo: { type: 'string' },
                        order: { type: 'integer' },
                        isVisible: { type: 'boolean' },
                    },
                },
                // ─── Media ───
                Media: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        filename: { type: 'string' },
                        originalName: { type: 'string' },
                        url: { type: 'string' },
                        mimeType: { type: 'string' },
                        size: { type: 'number', description: 'File size in bytes' },
                        alt: { type: 'string' },
                        createdAt: { type: 'string', format: 'date-time' },
                    },
                },
                // ─── Contact Message ───
                ContactMessage: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        name: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        phone: { type: 'string' },
                        subject: { type: 'string' },
                        message: { type: 'string' },
                        status: { type: 'string', enum: ['new', 'read', 'replied'] },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateContactMessageInput: {
                    type: 'object',
                    required: ['name', 'email', 'phone', 'subject', 'message'],
                    properties: {
                        name: { type: 'string', minLength: 2, maxLength: 100 },
                        email: { type: 'string', format: 'email' },
                        phone: { type: 'string', minLength: 7, maxLength: 20 },
                        subject: { type: 'string', minLength: 3, maxLength: 200 },
                        message: { type: 'string', minLength: 10, maxLength: 5000 },
                    },
                },
                // ─── Company Settings ───
                CompanySettings: {
                    type: 'object',
                    properties: {
                        _id: { type: 'string' },
                        nameAr: { type: 'string' },
                        nameEn: { type: 'string' },
                        yearsExperience: { type: 'string' },
                        clientsCount: { type: 'string' },
                        projectsCount: { type: 'string' },
                        satisfiedClientsCount: { type: 'string' },
                        successPercentage: { type: 'string' },
                        valuesAr: { type: 'array', items: { type: 'string' } },
                        valuesEn: { type: 'array', items: { type: 'string' } },
                        ourSeenAr: { type: 'string' },
                        ourSeenEn: { type: 'string' },
                        telephone: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        addressAr: { type: 'string' },
                        addressEn: { type: 'string' },
                        addressUrl: { type: 'string' },
                        logo: { type: 'string' },
                        createdAt: { type: 'string', format: 'date-time' },
                        updatedAt: { type: 'string', format: 'date-time' },
                    },
                },
                CreateCompanySettingsInput: {
                    type: 'object',
                    required: [
                        'nameAr', 'nameEn', 'yearsExperience', 'clientsCount',
                        'projectsCount', 'satisfiedClientsCount', 'successPercentage',
                        'ourSeenAr', 'ourSeenEn', 'telephone', 'email',
                        'addressAr', 'addressEn', 'addressUrl', 'logo',
                    ],
                    properties: {
                        nameAr: { type: 'string' },
                        nameEn: { type: 'string' },
                        yearsExperience: { type: 'string' },
                        clientsCount: { type: 'string' },
                        projectsCount: { type: 'string' },
                        satisfiedClientsCount: { type: 'string' },
                        successPercentage: { type: 'string' },
                        valuesAr: { type: 'array', items: { type: 'string' } },
                        valuesEn: { type: 'array', items: { type: 'string' } },
                        ourSeenAr: { type: 'string' },
                        ourSeenEn: { type: 'string' },
                        telephone: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        addressAr: { type: 'string' },
                        addressEn: { type: 'string' },
                        addressUrl: { type: 'string' },
                        logo: { type: 'string' },
                    },
                },
                // ─── Common Response Schemas ───
                Error: {
                    type: 'object',
                    properties: {
                        success: { type: 'boolean', example: false },
                        message: { type: 'string' },
                        statusCode: { type: 'number' },
                    },
                },
                PaginatedResponse: {
                    type: 'object',
                    properties: {
                        success: { type: 'boolean', example: true },
                        data: { type: 'array', items: {} },
                        pagination: {
                            type: 'object',
                            properties: {
                                total: { type: 'integer' },
                                page: { type: 'integer' },
                                size: { type: 'integer' },
                                totalPages: { type: 'integer' },
                                hasNextPage: { type: 'boolean' },
                                hasPrevPage: { type: 'boolean' },
                            },
                        },
                    },
                },
                SuccessResponse: {
                    type: 'object',
                    properties: {
                        success: { type: 'boolean', example: true },
                        message: { type: 'string' },
                    },
                },
                // ─── Auth Schemas ───
                LoginInput: {
                    type: 'object',
                    required: ['email', 'password'],
                    properties: {
                        email: { type: 'string', format: 'email' },
                        password: { type: 'string' },
                    },
                },
                LoginResponse: {
                    type: 'object',
                    properties: {
                        success: { type: 'boolean', example: true },
                        data: {
                            type: 'object',
                            properties: {
                                sessionId: { type: 'string' },
                                user: { $ref: '#/components/schemas/User' },
                            },
                        },
                    },
                },
                RegisterInput: {
                    type: 'object',
                    required: ['userName', 'email', 'password'],
                    properties: {
                        userName: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        password: { type: 'string', minLength: 6 },
                        role: { type: 'string', enum: ['admin', 'user'], default: 'user' },
                        tel: { type: 'string' },
                        yearsOfExp: { type: 'integer' },
                        descriptionAr: { type: 'string' },
                        descriptionEn: { type: 'string' },
                    },
                },
                ChangePasswordInput: {
                    type: 'object',
                    required: ['currentPassword', 'newPassword'],
                    properties: {
                        currentPassword: { type: 'string' },
                        newPassword: { type: 'string', minLength: 6 },
                    },
                },
            },
        },
        security: [
            {
                bearerAuth: [],
            },
        ],
        tags: [
            { name: 'Health Check', description: 'API health status' },
            { name: 'Authentication', description: 'User authentication endpoints' },
            { name: 'Users', description: 'User management (Admin only)' },
            { name: 'Projects', description: 'Project management' },
            { name: 'Categories', description: 'Project category management' },
            { name: 'Services', description: 'Service management' },
            { name: 'Departments', description: 'Department management' },
            { name: 'Quality Standards', description: 'Quality standards management' },
            { name: 'Employees', description: 'Employee management' },
            { name: 'Partners', description: 'Partner management' },
            { name: 'Media', description: 'Media file upload and management' },
            { name: 'Contact', description: 'Contact message management' },
            { name: 'Company Settings', description: 'Company information management' },
            { name: 'Site Settings', description: 'Site configuration management' },
        ],
    },
    apis: [
        './src/routes/*.ts',
        './src/controllers/*.ts',
    ],
};

export const swaggerSpec = swaggerJsdoc(options);
